import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/global/Navbar";
import SessionProvider from "@/components/global/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`relative font-global min-h-screen antialiased bg-gradient-bg from-bgGradient-start to-bgGradient-end px-8 overflow-x-hidden`}
        >
        <SessionProvider>
        <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
